<h1>numpy</h1>

<h2>Creating a numpy array</h2>

In [1]:
import numpy as np
ax = np.array([1,2,3,4,5])
print(ax,id(ax),len(ax))

[1 2 3 4 5] 4362772192 5


<h2>Specifying the type</h2>
<h3>Useful when reading a text stream directly into a numerical array</h3>

In [2]:
x=['1','2','3']
xi = np.array(x,'int')
xf = np.array(x,'float')
xs = np.array(x,'str')
print(xi,xf,xs,sep='\n')

[1 2 3]
[ 1.  2.  3.]
['1' '2' '3']


<h2>Basic operations</h2>

In [3]:
x = np.array([13,24,21.2,17.6,21.7],'float')
print(x.sum(),x.mean(),x.std(),sep='\n')

97.5
19.5
3.84291555983


<h2>Multi-dimensional arrays</h2>

In [6]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
print(ax)

[[  0.   1.   2.   3.   4.   5.]
 [ 10.  11.  12.  13.  14.  15.]
 [ 20.  21.  22.  23.  24.  25.]]


<h3>Indexing</h3>

In [7]:
ax[1,3] #indexing

13.0

<h3>Slicing</h3>

In [9]:
ax[1:3,2:4]
ax[:,2:]

array([[  2.,   3.,   4.,   5.],
       [ 12.,  13.,  14.,  15.],
       [ 22.,  23.,  24.,  25.]])

<h3>Reshaping</h3>


In [14]:
print(ax.shape)
ax.reshape(9,2)
#ax.reshape(10,3) # ValueError: cannot reshape array of size 18 into shape (10,3)

(3, 6)


array([[  0.,   1.],
       [  2.,   3.],
       [  4.,   5.],
       [ 10.,  11.],
       [ 12.,  13.],
       [ 14.,  15.],
       [ 20.,  21.],
       [ 22.,  23.],
       [ 24.,  25.]])

<h3>Creating initialized arrays</h3>

In [15]:
ax = np.arange(10)
print(ax)
ay = np.array([np.arange(10),np.arange(10)])
print(ay)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [18]:
ax = np.ones(10)
print(type(ax[0]), ax)

<class 'numpy.float64'> [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [19]:
ax = np.arange(10)**2
print(ax)

[ 0  1  4  9 16 25 36 49 64 81]


In [20]:
np.identity(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

<h3>Matrix multiplication</h3>


In [24]:
ax = np.arange(10)
ay = np.array([ax,ax])
#Scalar multiplication
ay*2
ay

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [26]:
ay.reshape(10,2)
ay.shape

(2, 10)

In [27]:
np.dot(ay,ay.reshape(10,2)) #Dot product

array([[220, 265],
       [220, 265]])

<h3>Comparing numpy arrays with lists</h3>

In [29]:
n=10
ax = np.array([np.arange(n)**2,np.arange(n)**3])
ay = ax.transpose()
print(ax)
print()
print(ay)

[[  0   1   4   9  16  25  36  49  64  81]
 [  0   1   8  27  64 125 216 343 512 729]]

[[  0   0]
 [  1   1]
 [  4   8]
 [  9  27]
 [ 16  64]
 [ 25 125]
 [ 36 216]
 [ 49 343]
 [ 64 512]
 [ 81 729]]


In [30]:
np.dot(ax,ay)

array([[ 15333, 120825],
       [120825, 978405]])

<h4>Functionalize this</h4>


In [53]:
def dotproduct(n):
    ax = np.array([np.arange(n)**2,np.arange(n)**3])
    ay = ax.transpose()
    import datetime
    start = datetime.datetime.now()
    np.dot(ax,ay)
    end = datetime.datetime.now()
    return end-start
    
dotproduct(10)    

datetime.timedelta(0, 0, 14)

<h4>Do the same with python lists</h4>


In [62]:
n = 10
x = [x**2 for x in range(n)]
y = [x**3 for x in range(n)]
ax = [x,y]
for X_row in ax:
    print(X_row)
print(ax)
print(zip(*ax))
ay = [list(i) for i in zip(*ax)]
print()
print(ay)
az = [list(Y_col) for Y_col in zip(*ay)]
print()
print(az)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]
[[0, 1, 4, 9, 16, 25, 36, 49, 64, 81], [0, 1, 8, 27, 64, 125, 216, 343, 512, 729]]

[[0, 0], [1, 1], [4, 8], [9, 27], [16, 64], [25, 125], [36, 216], [49, 343], [64, 512], [81, 729]]

[[0, 1, 4, 9, 16, 25, 36, 49, 64, 81], [0, 1, 8, 27, 64, 125, 216, 343, 512, 729]]


In [55]:
#print(zip(0,[0,1,2]))

In [74]:
def dot_product_lists(n):
    x = [x**2 for x in range(n)]
    y = [x**3 for x in range(n)]
    ax = [x,y]
    ay = [list(i) for i in zip(*ax)]
    import datetime
    start = datetime.datetime.now()
    total = [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*ay)] for X_row in ax]
    print(total)
    
    print()
    tlist = [] 
    for X_row in ax:
        rlist = []
        for Y_col in zip(*ay):
            total2 = 0
            for a,b in zip(X_row,Y_col):
                total2 = total2 + a * b
            rlist.append(total2)
        tlist.append(rlist)
        #[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*ay)]
    print(tlist)
    
    end = datetime.datetime.now()
    return end-start
    
dot_product_lists(10)

[[15333, 120825], [120825, 978405]]

[[15333, 120825], [120825, 978405]]


datetime.timedelta(0, 0, 318)

In [75]:
total = 0
for a,b in zip([0, 1, 4, 9, 16, 25, 36, 49, 64, 81],[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]):
    total += a * b
    
print(total)

for l in zip([0, 1, 4, 9, 16, 25, 36, 49, 64, 81],[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]):
    print(l)
  
total0 = 0
for a,b in zip([0, 1, 4, 9, 16, 25, 36, 49, 64, 81],[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]):
    total0 += a*b
total0    

15333
(0, 0)
(1, 1)
(4, 4)
(9, 9)
(16, 16)
(25, 25)
(36, 36)
(49, 49)
(64, 64)
(81, 81)


120825

In [76]:
for n in [10,100,1000,10000]:
    numpy_result = dotproduct(n)
    list_result = dot_product_lists(n)
    print(n,numpy_result,list_result,sep='\t')

[[15333, 120825], [120825, 978405]]

[[15333, 120825], [120825, 978405]]
10	0:00:00.000019	0:00:00.000647
[[1950333330, 161708332500], [161708332500, 13790714119050]]

[[1950333330, 161708332500], [161708332500, 13790714119050]]
100	0:00:00.000008	0:00:00.000425
[[199500333333300, 166167083333250000], [166167083333250000, 142357642856976190500]]

[[199500333333300, 166167083333250000], [166167083333250000, 142357642856976190500]]
1000	0:00:00.000007	0:00:00.001617
[[19995000333333333000, 166616670833333325000000], [166616670833333325000000, 1428071478571428404761905000]]

[[19995000333333333000, 166616670833333325000000], [166616670833333325000000, 1428071478571428404761905000]]
10000	0:00:00.000075	0:00:00.038078


<h3>Selecting elements from an np array</h3>

In [77]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
np.where(ax%2==0,1,0)

array([[1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0]])

In [78]:
ax

array([[  0.,   1.,   2.,   3.,   4.,   5.],
       [ 10.,  11.,  12.,  13.,  14.,  15.],
       [ 20.,  21.,  22.,  23.,  24.,  25.]])

In [79]:

#linalg, a linear algebra module
#functions dealing with polynomials, differentials, etc


In [80]:
import scipy
scipy.nanmean(x)

12.5

<h3>Random number support in numpy</h3>

In [85]:
np.random.normal(size=10)
np.random.normal(size=(100,100))
np.random.exponential()
np.random.exponential(1.0,size=(6,3))
np.random.randint(-10,10,size=(9,9))

array([[ -5,   4,  -6,   3,   4,  -3,   3,  -5, -10],
       [-10,  -5,   7,   1,   7,   3,   0,  -9,  -7],
       [  8,  -7,   9,  -9,  -7,  -1,   0,  -8,   3],
       [  8,   2, -10,   3,  -2,  -3,   5,  -1,   4],
       [ -7,  -4,  -8,   2,  -1,  -5,   3,   3,   9],
       [  7,   8,   2,  -3,   6,  -4,  -2,  -3,  -4],
       [  2,   1,   8,  -7,   0,  -9,   7,   2,   8],
       [  2,  -9,  -7,   2,  -4,  -9,   2,  -4,  -6],
       [ -3,  -6,   8,  -8,   2,  -9,  -2,   8,   5]])

In [91]:
x = [['0','1','2','3'],['4','5','6','7'],['8','9','10','11']]
ax=np.array(x,int)
ax.reshape(4,3)
ax.reshape(6,2)
# print(ax)
# print()
# ax.reshape(6,2)
# print(ax)
# print(ax, ax[2,2])

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [98]:
from numpy import pi
x = np.linspace( 0, 2*pi, 100 )
print(2 * pi)
f = np.sin(x)
print(f.max() - f.min())
print(np.ceil(f.max() -f.min()))

6.283185307179586
1.99974825535
2.0


In [111]:
a = np.arange(12)
b = a
print(b)
c = a.view()
c[0] = 12
print(c, b)
d = a.copy()
d[0] = 20
print(d, b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[12  1  2  3  4  5  6  7  8  9 10 11] [12  1  2  3  4  5  6  7  8  9 10 11]
[20  1  2  3  4  5  6  7  8  9 10 11] [12  1  2  3  4  5  6  7  8  9 10 11]


In [107]:
print(id(a), id(b), id(c), id(d))

4381612352 4381612352 4381493248 4381494368


In [115]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

96


In [118]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [123]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [131]:
color = np.arange(36).reshape(6,6)
color

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [132]:
color[(0,1,2,3,4),(1,2,3,4,5)]

array([ 1,  8, 15, 22, 29])

In [133]:
color[3:,[0,2,5]]

array([[18, 20, 23],
       [24, 26, 29],
       [30, 32, 35]])

In [135]:
Z = np.random.random(10)
print("Original array:")
print(Z)
Z.sort()
print("Sorted array:")
print(Z)

Original array:
[ 0.60089523  0.86713117  0.95116311  0.67580776  0.2098926   0.04091993
  0.49363412  0.58444582  0.72926354  0.63603272]
Sorted array:
[ 0.04091993  0.2098926   0.49363412  0.58444582  0.60089523  0.63603272
  0.67580776  0.72926354  0.86713117  0.95116311]


In [143]:
Z = np.random.uniform(0,1,10)
# print(Z)
# print()
# q = 0.5 
# print(np.abs(Z-q).argmin())
# print()
m = Z.flat[np.abs(Z-q).argmin()]
print(m)

0.492971615992
